@startuml
title UC1 - Registrer indgangskontrol
hide footbox
<style>
element {  
    BackGroundColor: #ded7d7;
}

sequenceDiagram {
    arrow {
        FontSize: 14;
        HorizontalAlignment: center;
    }

}
</style>

actor ":Medarbejder" as M
participant ":System" as S

M -> S: registrerMedarbejderID()
|||
M -> S: registrerIndgangskontrol()
|||
M -> S: registrerBremsekaliberID()
|||
M -> S: registrerVarenummer()
|||
S --> M: BremsekaliberTypen
|||
M -> S: godkendBremsekaliberTypen()
|||
M -> S: registrerDatoForIndgangskontrol()
|||
M -> S: gem()
|||
S --> M: Indgangskontrollen er gemt

@enduml